# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bild', models.BinaryField(blank=True, null=True)),
                ('HasEXIF', models.BooleanField(default=False)),
                ('CamModel', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField()),
                ('Scanned', models.BooleanField()),
                ('LastScan', models.DateTimeField(blank=True, null=True)),
                ('MD5Sum', models.CharField(blank=True, max_length=32, null=True)),
                ('encoding', models.CharField(blank=True, max_length=15, null=True)),
                ('ContentType', models.CharField(blank=True, max_length=15, null=True)),
                ('Cookies', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='Url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MetaGet.WebSite'),
        ),
    ]
