# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField()),
                ('Scanned', models.BooleanField()),
                ('LastScan', models.DateTimeField(blank=True, null=True)),
                ('MD5Sum', models.CharField(blank=True, max_length=32, null=True)),
                ('encoding', models.CharField(blank=True, max_length=15, null=True)),
                ('ContentType', models.CharField(blank=True, max_length=15, null=True)),
                ('Cookies', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
