# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TempFeld', models.CharField(blank=True, max_length=15, null=True)),
                ('Url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MetaGet.WebSite')),
            ],
        ),
    ]
