# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='MD5sum',
            field=models.CharField(default='Hi', max_length=32),
            preserve_default=False,
        ),
    ]
