# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='MD5Sum',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
