# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='TempFeld',
        ),
        migrations.AddField(
            model_name='image',
            name='Bild',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
