# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0002_website_md5sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='LastScan',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='Scanned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='Url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
