# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0003_image_datetimedigitized'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ExifImageHeight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='ExifImageWidth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
