# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0003_auto_20170101_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='HasEXIF',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
