# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0004_image_hasexif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='HasEXIF',
            field=models.BooleanField(default=False),
        ),
    ]
