# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0004_auto_20170101_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='Scanned',
            field=models.BooleanField(default=False),
        ),
    ]
