# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0004_website_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='LastScan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='MD5Sum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='encoding',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
