# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaGet', '0005_auto_20161231_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ContentType',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='encoding',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
